### PR TITLE
Drop dead/unused code

### PR DESCRIPTION
**Pull request by ChALkeR**
This removes only complete functions / definitions.

Things should work if they compile (and they should compile afaik).

### CODE REVIEW

**Review by gutenye — APPROVED** [review]
utACK

**Comment by gutenye** [comment]
Build on desktop, got these errors
```
/app/src/submodules/mymonero-core-cpp/src/monero_wallet_utils.cpp:302:3: error: too many arguments to function call, expected at most 3, have 4
                decodedSeed_retVals.from_legacy16B_lw_seed // assumed set if r
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/app/src/submodules/mymonero-core-cpp/contrib/monero-core-custom/cryptonote_basic/account.h:76:5: note: 'generate' declared here
    crypto::secret_key generate(const crypto::secret_key& recovery_key = crypto::secret_key(), bool recover = false, bool two_random = false);
    ^
/app/src/submodules/mymonero-core-cpp/src/monero_wallet_utils.cpp:359:3: error: too many arguments to function call, expected at most 3, have 4
                from_legacy16B_lw_seed // assumed set if r
                ^~~~~~~~~~~~~~~~~~~~~~
/app/src/submodules/mymonero-core-cpp/contrib/monero-core-custom/cryptonote_basic/account.h:76:5: note: 'generate' declared here
    crypto::secret_key generate(const crypto::secret_key& recovery_key = crypto::secret_key(), bool recover = false, bool two_random = false);
    ^
/app/src/submodules/mymonero-core-cpp/src/monero_wallet_utils.cpp:488:78: error: too many arguments to function call, expected at most 3, have 4
                        expected_account.generate(sec_seed, true/*recover*/, false/*two_random*/, from_legacy16B_lw_seed);
                        ~~~~~~~~~~~~~~~~~~~~~~~~~                                                 ^~~~~~~~~~~~~~~~~~~~~~
/app/src/submodules/mymonero-core-cpp/contrib/monero-core-custom/cryptonote_basic/account.h:76:5: note: 'generate' declared here
    crypto::secret_key generate(const crypto::secret_key& recovery_key = crypto::secret_key(), bool recover = false, bool two_random = false);
    ^
In file included from /app/src/submodules/mymonero-core-cpp/src/monero_wallet_utils.cpp:33:
In file included from /app/src/submodules/mymonero-core-cpp/src/monero_wallet_utils.hpp:37:
/app/src/submodules/mymonero-core-cpp/contrib/monero-core-custom/serialization/binary_archive.h:195:28: warning: shift count >= width of type [-Wshift-count-overflow]
      if (1 < sizeof(T)) v >>= 8;
                           ^   ~
/app/src/submodules/mymonero-core-cpp/contrib/monero-core-custom/serialization/binary_archive.h:188:5: note: in instantiation of function template specialization
      'binary_archive<true>::serialize_uint<unsigned char>' requested here
    serialize_uint(static_cast<typename boost::make_unsigned<T>::type>(v));
    ^
/app/src/submodules/mymonero-core-cpp/contrib/monero-core-custom/serialization/binary_archive.h:228:5: note: in instantiation of function template specialization
      'binary_archive<true>::serialize_int<unsigned char>' requested here
    serialize_int(t);
    ^
1 warning and 3 errors generated.
```

**Comment by ChALkeR** [comment]
@gutenye investigating.

**Comment by ChALkeR** [comment]
@gutenye That shouldn't happen. There is no `from_legacy16B_lw_seed` in https://github.com/ExodusMovement/mymonero-core-cpp/tree/react-native-integration

Refs: https://github.com/ExodusMovement/mymonero-core-cpp/commit/7de9e28e85b9de73fa524078f2ea3557e7ed70a0

**Review by gutenye — APPROVED** [review]
tACK (build pass, send and receive XMR)

**Review by Sekhmet — APPROVED** [review]
tACK

Built for react native.

**Pull request merged**
