### PR TITLE
Drop some unused code

### PR DESCRIPTION
**Pull request by ChALkeR**
This is not final yet, but testing if this builds/works would help.

### CODE REVIEW

**Review by Sekhmet — APPROVED** [review]
tACK

Tested sending and receiving on iOS.

**Comment by ChALkeR** [comment]
This has whitespace issues, don't merge until those are resolved to minimize future conflicts. There shouldn't be a hurry to merge this (per @sonaye comment).

**Comment by Sekhmet** [comment]
@ChALkeR 
Tested it on both iOS and Android syncing 150k blocks of account history and sending.

**Comment by ChALkeR** [comment]
Updated, no insertions now, only deletions.
No actual code changes since the review, only formatting.

Should be ready now, sorry for the delay.

**Comment by Sekhmet** [comment]
Replaced with https://github.com/ExodusMovement/monero-core-custom/pull/7

**Pull request closed without merging**
